<?php

use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\Core\Form\FormStateInterface;    
use Drupal\Core\Ajax\AjaxResponse;
use Drupal\Core\Form\FormBase;
use Drupal\Core\Form\FormInterface;
use Drupal\Core\Ajax\InvokeCommand;


function employee_ajax_form_submit(array &$form, FormStateInterface $form_state) {
  $response = new AjaxResponse();
  $message = $form_state->getValue('employee_name') . ' has been saved successfully.';
  
  $response->addCommand(new HtmlCommand('#ajax-response-message', $message));
  
  return $response;
}

